import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { AppProgressBar } from 'next-nprogress-bar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" suppressHydrationWarning>
      <body className={`antialiased font-IransansR`}>
        <AppProgressBar
          height="4px"
          color="#10b981"
          options={{ showSpinner: false }}
          shallowRouting
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
